# baseURL = "https://example.com"
# languageCode = "en"
# title = "Website of Jane Doe"
# theme = "anatole"



baseURL = "http://r0nus.github.io/"
languageCode = "en-us"
# DefaultContentLanguage = "en"
title = "The r0nus Blog"
theme="anatole"
summarylength = 10

# [params]
# googleAnalytics = "G-Z6JGW7HN6D"

# [params.math]
# enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
# use = "katex"  # options: "katex", "mathjax". default is "katex".







# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

pygmentsCodefencesGuessSyntax = true
