baseURL = "http://r0nus.github.io/"
languageCode = "en-us"
title = "The r0nus Blog"
theme="anatole"

[params]
profilePicture = "images/profile.jpg"
description = """
Blogging from home
"""
doNotLoadAnimations = true 
googleAnalytics = "G-Z6JGW7HN6D"
displayMode = "dark"
images = ["images/site-feature-image.png"]
enableMediumZoom = false
contentratio = 0.8

[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".



pygmentsCodeFences = true
pygmentsUseClasses = true


[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/about/index.html"
